## <center>Carregando os algoritmos para implementação: Análise risco de crédito<center>


In [1]:
import pickle
import numpy as np

In [5]:

with open("base.pkl", "rb") as df:
    X_base_treinamento, y_base_treinamento, X_base_teste, y_base_teste = pickle.load(df)

In [6]:
X_base = np.concatenate((X_base_treinamento, X_base_teste), axis = 0)
y_base = np.concatenate((y_base_treinamento, y_base_teste), axis = 0)

In [7]:
arvore_decisao = pickle.load(open("arvore_decisao_finalizado.sav", "rb"))
random_forest = pickle.load(open("random_forest_finalizado.sav", "rb"))
knn = pickle.load(open("knn_finalizado.sav", "rb"))
svm = pickle.load(open("svm_finalizado.sav", "rb"))
rede_neural = pickle.load(open("rede_neural_finalizado.sav", "rb"))

# Testando os algoritmos com novos Registro:

* `novo_registro0 = Paga`
* `novo_registro1 = Não Paga`

Se o resultado do algoritmo previsor for o mesmo das variaveis `novo_registro0 | novo_registro1` o algoritmo acertou a previsão de um possivel novo registro de entrada. 

In [9]:
#Testando os algoritmos carregados. 
novo_registro0 = X_base[0] #Paga = 0

In [10]:
novo_registro0

array([-1.3754462 ,  0.50631087,  0.10980934])

In [11]:
novo_registro1 = X_base[1999] #Não paga = 1


In [12]:
novo_registro1

array([-1.03572293, -0.93978122,  0.04244312])

In [13]:
#Colocando em formato de matriz
novo_registro0 = novo_registro0.reshape(1,-1)
novo_registro0.shape

(1, 3)

In [14]:
# Colocando em formato de matriz
novo_registro1 = novo_registro1.reshape(1,-1)
novo_registro1.shape

(1, 3)

<center>Teste de um novo registro no algoritmo de Árvore de Decisão<center>

In [15]:
arvore_decisao.predict(novo_registro0)

array([0], dtype=int64)

*acertou*

In [16]:
arvore_decisao.predict(novo_registro1)

array([1], dtype=int64)

*acertou*

<center>Teste de um novo registro no algoritmo de Random Forest<center>

In [17]:
random_forest.predict(novo_registro0)

array([0], dtype=int64)

*acertou*

In [18]:
random_forest.predict(novo_registro1)

array([1], dtype=int64)

*acertou*

<center>Teste de um novo registro no algoritmo de KNN<center>

In [19]:
knn.predict(novo_registro0)

array([0], dtype=int64)

*acertou*

In [20]:
knn.predict(novo_registro1)

array([1], dtype=int64)

*acertou*

<center>Teste de um novo registro no algoritmo de SVM<center>

In [21]:
svm.predict(novo_registro0)

array([0], dtype=int64)

*acertou*

In [22]:
svm.predict(novo_registro1)

array([1], dtype=int64)

*acertou*

<center>Teste de um novo registro no algoritmo de Rede Neural<center>

In [23]:
rede_neural.predict(novo_registro0)

array([0], dtype=int64)

*acertou*

In [24]:
rede_neural.predict(novo_registro1)

array([1], dtype=int64)

*acertou*

# FIM